# Name of the GitHub Actions workflow
name: Build, Scan, and Push Docker Image to ACR

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering

# --- NEW: Grant permissions for CodeQL results ---
permissions:
  actions: read
  contents: read
  security-events: write # Allows uploading CodeQL results

env:
  ACR_NAME: 'ACRLFS' # Your existing ACR name

jobs:
  build-scan-and-push:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checks out your repository code
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v4 

    # --- Initialize CodeQL ---
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: python 
        # queries: security-extended,security-and-quality # Optional: Use more queries if needed

    # --- Build step required by CodeQL ---
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' 
    - name: Install dependencies for CodeQL analysis
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # --- Perform CodeQL Analysis ---
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3

    # --- Existing Steps ---
    # Step 2: Logs into your Azure account
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Logs into your private Azure Container Registry (ACR).
    - name: 'Login to Azure Container Registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # Step 4: Builds the Docker image and pushes it to ACR.
    - name: Build and Push Docker image to ACR
      run: |
        docker build . -t ${{ env.ACR_NAME }}.azurecr.io/finder-app:${{ github.run_number }}
        docker push ${{ env.ACR_NAME }}.azurecr.io/finder-app:${{ github.run_number }}

    # Step 5: (Optional) Logout from ACR
    - name: Logout from Azure Container Registry
      run: docker logout ${{ env.ACR_NAME }}.azurecr.io
