name: Build and Push Docker Image to ACR

on:
  push:
    branches: [ main ]        # Trigger on pushes to main branch
  workflow_dispatch:          # Allows manual trigger

env:
  ACR_NAME: 'ACRLFS'          # Your Azure Container Registry name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Login to Azure Container Registry
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 4️⃣ Build Docker image with caching
      - name: Build Docker image
        run: |
          docker build --cache-from ${{ env.ACR_NAME }}.azurecr.io/finder-app:latest \
                       -t ${{ env.ACR_NAME }}.azurecr.io/finder-app:${{ github.sha }} .

      # 5️⃣ Push Docker image with SHA tag
      - name: Push Docker image
        run: |
          docker push ${{ env.ACR_NAME }}.azurecr.io/finder-app:${{ github.sha }}
          docker tag ${{ env.ACR_NAME }}.azurecr.io/finder-app:${{ github.sha }} \
                     ${{ env.ACR_NAME }}.azurecr.io/finder-app:latest
          docker push ${{ env.ACR_NAME }}.azurecr.io/finder-app:latest
